/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IssuesImport } from './routes/issues'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ReposLazyImport = createFileRoute('/repos')()

// Create/Update Routes

const ReposLazyRoute = ReposLazyImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/repos.lazy').then((d) => d.Route))

const IssuesRoute = IssuesImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesImport
      parentRoute: typeof rootRoute
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/issues': typeof IssuesRoute
  '/repos': typeof ReposLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/issues': typeof IssuesRoute
  '/repos': typeof ReposLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/issues': typeof IssuesRoute
  '/repos': typeof ReposLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/issues' | '/repos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/issues' | '/repos'
  id: '__root__' | '/' | '/issues' | '/repos'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IssuesRoute: typeof IssuesRoute
  ReposLazyRoute: typeof ReposLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IssuesRoute: IssuesRoute,
  ReposLazyRoute: ReposLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/issues",
        "/repos"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/issues": {
      "filePath": "issues.tsx"
    },
    "/repos": {
      "filePath": "repos.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
